name: Github Pages

on:
  workflow_call:
    inputs:
      publishGitHubPages:
        required: false
        type: boolean
        default: false

jobs:
  github-pages:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Create required folder structure
        if: inputs.publishGitHubPages
        run: |
          mkdir ./${{ github.repository }}
          mv ./README.md ${{ github.repository }}

      - name: Deploy
        if: inputs.publishGitHubPages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./${{ github.repository }}
          enable_jekyll: true
