name: Helm Chart Release

on:
  workflow_call:
    inputs:
      nameOverride:
        required: false
        type: string
        default: 'xy,xy'
      helmChartDir:
        required: false
        type: string
        default: 'helm'
      helmRepo:
        required: false
        type: string
        default: 'helm-charts'
      appVersion:
        required: true
        type: string
      slackChannel:
        required: false
        type: string
        default: 'ci_qm_test'
    secrets:
      token:
        required: true
      repoUser:
        required: true
      repoPassword:
        required: true
      repoURL:
        required: true
      slackWebhookURL:
        required: false
      teamsWebhookURL:
        required: false
      appVersionPrefix:
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{github.sha}}
          submodules: true
          token: ${{ secrets.token }}

      - uses: actions/checkout@v3
        with:
          repository: levigo/github-actions
          ref: refs/tags/latest
          path: actions
          token: ${{ secrets.token }}

      - run: |
          git status
          git submodule update --remote helm
          git status
          ls -lahn helm
          cd helm
          git status || true

      - uses: ./actions/helm-chart
        with:
          nameOverride: ${{ inputs.nameOverride }}
          helmChartDir: ${{ inputs.helmChartDir }}
          helmRepo: ${{ inputs.helmRepo }}
          appVersion: ${{ inputs.appVersion }}
          appVersionPrefix: ${{ secrets.appVersionPrefix }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          repoUser: ${{ secrets.repoUser }}
          repoPassword: ${{ secrets.repoPassword }}
          repoURL: ${{ secrets.repoURL }}

      - uses: ./actions/notify-developers
        with:
          teamsWebhookURL: ${{ secrets.teamsWebhookURL }}
          slackWebhookURL: ${{ secrets.slackWebhookURL }}
          slackChannel: ${{ inputs.slackChannel }}
          slackMessage: Released Helm Chart ${{ inputs.helmChartName }} for AppVersion ${{ inputs.appVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        if: always()
