name: Continuous Integration

on:
  workflow_call:
    inputs:
      sonarAnalysisEnabled:
        required: false
        type: boolean
        default: true
      skipTests:
        required: false
        type: boolean
        default: false
      mattermostChannel:
        required: false
        type: string
        default: 'ci_js'
      notifyMattermost:
        required: false
        type: boolean
        default: true
      notifyTeams:
        required: false
        type: boolean
        default: false
      scanImage:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
      # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
      MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
      # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
      # when running from the command line.
      # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Prepare maven settings
        env:
          REGISTRY_URL: ${{ secrets.LEVIGO_NEXUS_REGISTRY_RELEASES }}
          REPOSITORY_URL: ${{ secrets.LEVIGO_NEXUS_REPO_ALL }}
          REPOSITORY_USERID: ${{ secrets.LEVIGO_NEXUS_USERNAME }}
          REPOSITORY_CREDENTIALS: ${{ secrets.LEVIGO_NEXUS_PASSWORD }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: |
          mkdir -p ~/.m2
          envsubst < ./.github/settings.xml > ~/.m2/settings.xml

      ## Build and Test
      - name: Perform build
        if: inputs.skipTests == false
        run: mvn $MAVEN_CLI_OPTS verify -Dmaven.test.failure.ignore=true

      ## Build and Test + Scan
      - name: Perform build
        if: ${{ inputs.skipTests == false && inputs.scanImage == true }}
        env:
          REGISTRY_URL: ${{ secrets.LEVIGO_NEXUS_REGISTRY_RELEASES }}
        run: |
          mvn $MAVEN_CLI_OPTS verify \
            -Dmaven.test.failure.ignore=true \
            -DenableDocker \
            -Ddocker.registry.from=${REGISTRY_URL} \
            -Djib-maven-plugin.goal=dockerBuild
          echo "CONTAINER_IMAGE=$(jq -r .image target/jib-image.json)" >> $GITHUB_ENV

      - name: Scan container image
        continue-on-error: true
        if: ${{ inputs.skipTests == false && inputs.scanImage == true }}
        uses: azure/container-scan@f9af925b897d8af5f7e0026b8bca9346261abc93
        with:
          image-name: ${{ env.CONTAINER_IMAGE }}

      - name: Publish Test Report
        if: inputs.skipTests == false
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_test_failures: true
          fail_if_no_tests: true

      ## Build without running Tests
      - name: Perform build
        if: inputs.skipTests
        run: mvn $MAVEN_CLI_OPTS verify -DskipTests

      ## Static code analysis with sonarqube
      - name: Perform sonar analysis
        if: inputs.sonarAnalysisEnabled
        continue-on-error: true
        run: mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.scm.disabled=true -Dsonar.qualitygate.wait=true

      - name: Notify Mattermost
        uses: hennejg/slack-build-notifier@v1.1
        if: inputs.notifyMattermost
        with:
          username: GitHub
          icon_emoji: octocat
          channel: ${{ inputs.mattermostChannel }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify teams
        uses: toko-bifrost/ms-teams-deploy-card@master
        if: inputs.notifyTeams
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.JS_TEAMS_WEBHOOK_URL }}
          show-on-start: false
          show-on-exit: true
          show-on-failure: true
          card-layout-exit: complete
          timezone: "Europe/Berlin"
          include-files: false
