name: sbom-maven-create

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: '${{ github.event.repository.default_branch }}'
      jdkVersion:
        description: 'The JDK version to use. (defaults to "11")'
        required: false
        type: string
        default: '11'
      javaDistribution:
        description: 'The Java distribution to use. (defaults to eclipse "temurin")'
        required: false
        type: string
        default: 'temurin'
      mavenRootDirectory:
        description: 'The directory with the root pom.xml. (defaults to project root)'
        required: false
        type: string
        default: '${{ github.workspace }}'
    outputs:
      sbomFile: "${{ inputs.mavenRootDirectory }}target/bom.json"

permissions:
  contents: write

env:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

jobs:
  scan:
    runs-on: ubuntu-22.04
    timeout-minutes: ${{ inputs.timeoutMinutes}}
    env:
      REPO_NAME: ${{ github.repository }}
      SBOM_FILE: "${{ inputs.mavenRootDirectory }}target/bom.json"
      TRIVY_RESULT_FILE: 'trivy-cyclonedx-sbom.txt'

    steps:
      - name: Checkout branch ${{ inputs.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.javaDistribution }}
          java-version: ${{ inputs.jdkVersion }}
          cache: 'maven'

      - name: Prepare maven settings
        env:
          REGISTRY_URL: ${{ secrets.LEVIGO_NEXUS_REGISTRY_RELEASES }}
          REPOSITORY_URL: ${{ secrets.LEVIGO_NEXUS_REPO_ALL }}
          REPOSITORY_USERID: ${{ secrets.LEVIGO_NEXUS_USERNAME }}
          REPOSITORY_CREDENTIALS: ${{ secrets.LEVIGO_NEXUS_PASSWORD }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        run: |
          mkdir -p ~/.m2
          envsubst < ./.github/settings.xml > ~/.m2/settings.xml

      - name: create SBOM with cyclonedx-maven-plugin
        id: create-sbom
        working-directory: ${{ inputs.mavenRootDirectory }}
        run: |
          mvn ${{ env.MAVEN_CLI_OPTS }} org.cyclonedx:cyclonedx-maven-plugin:2.7.11:makeAggregateBom -DoutputFormat=json
